GRANT USAGE ON SCHEMA {{base}},{{policy}},{{staging}},{{corpus}} TO {{role_guard}};
GRANT SELECT ON ALL TABLES IN SCHEMA {{policy}},{{staging}},{{corpus}} TO {{role_guard}};
GRANT SELECT ON {{base}}.identity_collections TO {{role_guard}};
GRANT INSERT,UPDATE ON {{policy}}.revision_head TO {{role_guard}};
GRANT INSERT ON {{policy}}.audit_event TO {{role_guard}};
GRANT UPDATE ON {{staging}}.staged_artifact TO {{role_guard}};
GRANT USAGE ON SCHEMA {{policy}},{{corpus}} TO {{role_serving}},{{role_release}};
GRANT USAGE ON SCHEMA {{policy}},{{staging}} TO {{role_acquisition}};
GRANT USAGE ON SCHEMA {{policy}} TO {{role_review}};
GRANT SELECT ON {{corpus}}.eligible_metadata TO {{role_serving}},{{role_release}};
GRANT SELECT,INSERT,UPDATE ON {{corpus}}.metadata_projection TO {{role_release}};
GRANT SELECT,INSERT,UPDATE ON {{staging}}.staged_artifact TO {{role_acquisition}};
GRANT SELECT,INSERT ON {{policy}}."controller_record" TO {{role_review}};
GRANT SELECT,INSERT ON {{policy}}."privacy_review" TO {{role_review}};
GRANT SELECT,INSERT ON {{policy}}."acquisition_assessment" TO {{role_review}};
GRANT SELECT,INSERT ON {{policy}}."collection_decision" TO {{role_review}};
GRANT SELECT,INSERT ON {{policy}}."verification_policy" TO {{role_review}};
GRANT SELECT,INSERT ON {{policy}}."version_override" TO {{role_review}};
GRANT SELECT,INSERT ON {{policy}}."verification_material" TO {{role_review}};
GRANT SELECT ON {{policy}}."evidence" TO {{role_review}};
GRANT SELECT ON {{policy}}."version_binding" TO {{role_review}};
GRANT SELECT ON {{policy}}.audit_event TO {{role_review}};
GRANT EXECUTE ON FUNCTION {{policy}}.current_actor() TO {{role_review}},{{role_acquisition}},{{role_release}};
GRANT EXECUTE ON FUNCTION {{policy}}.assigned(text,text) TO {{role_serving}},{{role_review}},{{role_acquisition}},{{role_release}};
GRANT EXECUTE ON FUNCTION {{policy}}.metadata_allowed(text) TO {{role_serving}},{{role_release}};
GRANT EXECUTE ON FUNCTION {{policy}}.staging_allowed(uuid,bigint,text,text) TO {{role_acquisition}};
GRANT EXECUTE ON FUNCTION {{policy}}.review_permission(text,text,text) TO {{role_review}};
GRANT EXECUTE ON FUNCTION {{policy}}.lock_collection(text,bigint) TO {{role_review}},{{role_release}};
GRANT EXECUTE ON FUNCTION {{policy}}.lock_approval_inputs(text,bigint,bigint) TO {{role_release}};
GRANT EXECUTE ON FUNCTION {{policy}}.erase_staged(uuid) TO {{role_acquisition}};
